###################################################
# KEYWORD를 정의 합니다.							  #
###################################################
ADDITION = +
SUBTRACT = -
MULTIPLY = *
RIGHT_DIVIDE = /
LEFT_DIVIDE = \\
#최우선 연산자 :  
ASSIGNMENT = =
LEFT_PAREN =  (
RIGHT_PAREN = )
LEFT_BRACE = {
RIGHT_BRACE = }
#지수 연산자 : ^√
POWER = ^
ROOT = √ 
#증가 연산자감소 연산자
INCREMENT = ++
DECREMENT = --
#증가 할당 연산자감소 할당 연산자
INCREMENT_ASSIGNMENT = +=
DECREMENT_ASSIGNMENT = -=
#관계 연산자 : <==><=>=!=
LESS_THAN = <
EQUAL = ==
GREATER_THAN = >
LESS_EQUAL = <=
GREATER_EQUAL = >=
NOT_EQUAL = !=
#논리 연산자 : 논리합논리곱논리부정
OR = OR
AND = AND
NOT = NOT
### 삼항 연산자 : ?:
QUESTION = ?
COLON = :
SEMICOLON = ;
### 순차 연산자 : ,
COMMA = ,
### 내적연산 ###
DOT = .
# '.*' 요소별 곱셈
DOT_MULTIPLY = .*
# './' 요소별 오른쪽 나눗셈
DOT_RIGHT_DIVIDE = ./
# '.\' 요소별 왼쪽 나눗셈
DOT_LEFT_DIVIDE = .\\
# '.^' 요소별 거듭제곱
DOT_POWER = .^
# '.√' 요소별 제곱근
DOT_ROOT = .√
#행렬 재배열
RESHAPE = .RESHAPE
#' 전치 행렬
TRANSPOSE = TRANSPOSE
#백분율 : %
PERCENT = %
#Shift 연산 : <<>>>>>
DOUBLE_LESS_THAN = <<
DOUBLE_GREATER_THAN = >>
TRIPLE_GREATER_THAN = >>>
#BIT 논리 연산자 : |&~^ = #)
BIT_OR = |
BIT_AND = &
BIT_NOT = ~
BIT_XOR = @
#문자열
STRING = \'
#내부함수
ROUND = ROUND
ROUND_UP = ROUND_UP
ROUND_DOWN = ROUND_DOWN
LARGE = LARGE
SMALL = SMALL
SIN = SIN
COS = COS
TAN = TAN
MOD = MOD
ABS = ABS
LOG = LOG
HEX = HEX
OCT = OCT
BIN = BIN
TOHEX = TOHEX
TOOCT = TOOCT
TOBIN = TOBIN
TERNARY_OPERATION = TERNARY_OPERATION
#Keywords
IF = IF
ELSEIF = ELSEIF
ELSE = ELSE
PI = PI
LOG_E = LOG_E
TRUE = TRUE
FALSE = FALSE
